### ISSUE TITLE
Flask-CQLAlchemy getting issue NoHostAvailable

### ISSUE THREAD

**Issue by fercam24** [thegeorgeous/flask-cqlalchemy#18]
Hi George Thomas,

I installed your python library for Flask but I'm getting issues. I created a Model like in your example, then in a flask view I have a route to get all datas from a columnfamily. But when I do a GET request on this route, I get this error :

```
[Thu Aug 11 15:40:58.637843 2016] [wsgi:error] [pid 6021] [client 192.168.20.8:47626]
[Thu Aug 11 15:40:58.637912 2016] [wsgi:error] [pid 6021] ERROR:run:Exception on /operations/ [GET]
[Thu Aug 11 15:40:58.637923 2016] [wsgi:error] [pid 6021] Traceback (most recent call last):
[Thu Aug 11 15:40:58.637927 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1988, in wsgi_app
[Thu Aug 11 15:40:58.637931 2016] [wsgi:error] [pid 6021]     response = self.full_dispatch_request()
[Thu Aug 11 15:40:58.637934 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1641, in full_dispatch_request
[Thu Aug 11 15:40:58.637938 2016] [wsgi:error] [pid 6021]     rv = self.handle_user_exception(e)
[Thu Aug 11 15:40:58.637941 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1544, in handle_user_exception
[Thu Aug 11 15:40:58.637945 2016] [wsgi:error] [pid 6021]     reraise(exc_type, exc_value, tb)
[Thu Aug 11 15:40:58.637949 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
[Thu Aug 11 15:40:58.637952 2016] [wsgi:error] [pid 6021]     raise value
[Thu Aug 11 15:40:58.637956 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1639, in full_dispatch_request
[Thu Aug 11 15:40:58.637959 2016] [wsgi:error] [pid 6021]     rv = self.dispatch_request()
[Thu Aug 11 15:40:58.637963 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1625, in dispatch_request
[Thu Aug 11 15:40:58.637967 2016] [wsgi:error] [pid 6021]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Aug 11 15:40:58.637970 2016] [wsgi:error] [pid 6021]   File "/var/www/html/cassandrarest/app/main/views.py", line 20, in getOperations
[Thu Aug 11 15:40:58.637974 2016] [wsgi:error] [pid 6021]     if not operations:
[Thu Aug 11 15:40:58.637977 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/cassandra/cqlengine/query.py", line 351, in __len__
[Thu Aug 11 15:40:58.637981 2016] [wsgi:error] [pid 6021]     self._execute_query()
[Thu Aug 11 15:40:58.637984 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/cassandra/cqlengine/query.py", line 386, in _execute_query
[Thu Aug 11 15:40:58.637988 2016] [wsgi:error] [pid 6021]     self._result_generator = (i for i in self._execute(self._select_query()))
[Thu Aug 11 15:40:58.637992 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/cassandra/cqlengine/query.py", line 318, in _execute
[Thu Aug 11 15:40:58.637995 2016] [wsgi:error] [pid 6021]     result = _execute_statement(self.model, statement, self._consistency, self._timeout)
[Thu Aug 11 15:40:58.638008 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/cassandra/cqlengine/query.py", line 1359, in _execute_statement
[Thu Aug 11 15:40:58.638013 2016] [wsgi:error] [pid 6021]     return connection.execute(s, params, timeout=timeout)
[Thu Aug 11 15:40:58.638017 2016] [wsgi:error] [pid 6021]   File "/usr/local/lib/python3.4/dist-packages/cassandra/cqlengine/connection.py", line 170, in execute
[Thu Aug 11 15:40:58.638020 2016] [wsgi:error] [pid 6021]     result = session.execute(query, params, timeout=timeout)
[Thu Aug 11 15:40:58.638024 2016] [wsgi:error] [pid 6021]   File "cassandra/cluster.py", line 1941, in cassandra.cluster.Session.execute (cassandra/cluster.c:33642)
[Thu Aug 11 15:40:58.638028 2016] [wsgi:error] [pid 6021]   File "cassandra/cluster.py", line 3629, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:69369)
[Thu Aug 11 15:40:58.638034 2016] [wsgi:error] [pid 6021] cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 192.168.20.6 DC1>: error('required argument is not an integer',), <Host: 192.168.20.9 DC1>: error('required argument is not an integer',), <Host: 192.168.20.5 DC1>: error('required argument is not an integer',), <Host: 192.168.20.4 DC1>: error('required argument is not an integer',)})
```

My flask app structure looks like below:

```
run.py
|
app
   |_config.py
   |_db_config.py (Used to instanciate CQLAlchemy to avoid cyclic imports in my project)
   |_models.py (where I have my class model)
   |_main
         |_views.py
```

``` python
#run.py
from flask import Flask
from app.config import Production, Testing
from flask_cqlalchemy import CQLAlchemy

app = Flask(__name__)
app.config.from_object(Testing)
app._static_folder = "./app/static"

from app.main.views import main as main_blueprint
app.register_blueprint(main_blueprint, url_prefix='/operations')

from app.db_config import db


if __name__ == "__main__":
        app.run()
```

---

``` python
#app/config.py
import os

class Config(object):
        """Default Flask configuration inherited by all environments. Use this for development environments."""
        PROJECT_ROOT = os.path.dirname(os.path.realpath(__file__))
        DEBUG = True
        TESTING = False
        CSRF_ENABLED = True
        CSRF_SESSION_KEY = "xxx"
        SECRET_KEY = "xxx"
        HOST = "0.0.0.0"
        PORT = 80
        CASSANDRA_HOSTS = ['192.168.20.9', '192.168.20.5']
        CASSANDRA_CONSISTENCY = "QUORUM"
        CASSANDRA_SETUP_KWARGS = {'protocol_version': 3}


class Production(Config):
        DEBUG = False
        CASSANDRA_KEYSPACE = "myKeyspace"

class Testing(Config):
        TESTING = True
        CASSANDRA_KEYSPACE = "myKeyspace_test"
```

---

``` python
#app/db_config.py
from flask_cqlalchemy import CQLAlchemy
from run import app

db = CQLAlchemy(app)
```

---

``` python
#app/models.py
from app.db_config import db

class Operations(db.Model):
        client = db.columns.Text(partition_key=True, required=True)
        type = db.columns.Text(primary_key=True, required=True)
        probe_id = db.columns.Text(primary_key=True, required=True)
        op_start = db.columns.DateTime(primary_key=True, required=True)
        op_end = db.columns.DateTime(primary_key=True, required=True)
        parameters = db.columns.Map(db.columns.Text, db.columns.Text)
        docs = db.columns.Map(db.columns.Text, db.columns.Text)
        requester = db.columns.Text()
        request_date = db.columns.DateTime()
        event_id = db.columns.Text()
        status = db.columns.Text()
```

---

``` python
#app/main/views.py
from __future__ import print_function
from flask import Blueprint, jsonify, request
from app.models import Operations
from app.db_config import db
from datetime import datetime
import sys

main = Blueprint('operations', __name__)

@main.route("/", methods=["GET"])
def getOperations():
        operations = Operations.objects.all()
        if not operations:
                resp = jsonify({'operations': ''})
                resp.status_code = 200
                return resp
        op_json = []
        for operation in operations:
                op_json.append(
                        {
                                'client' : operation.client,
                                'type' : operation.type,
                                'probe_id' : operation.probe_id,
                                'op_start' : operation.op_start,
                                'op_end' : operation.op_end,
                                'parameters' : operation.parameters,
                                'docs' : operation.docs,
                                'requester' : operation.requester,
                                'request_date' : operation.request_date,
                                'event_id' : operation.event_id,
                                'status' : operation.status
                        }
                )
        resp = jsonify({'operations': op_json})
        resp.status_code = 200
        return resp
```

Any idea why I get this NoHostAvailable? nodetool status tells me that everything is ok, and before using your library I was using the cassandra-driver native and it was working fine. And about db_sync() didn't really understood how I have to use it.

Versions used:

```
cassandra = 3.0.5
cassandra_driver = 3.5.0
Flask-CQLAlchemy = 1.2.0
Flask = 0.11.1
```

Thanks in advance and wish you a great day.

**Comment by fercam24** [comment]
Hi, 
I finally solved the problem, on config 

``` python
CASSANDRA_CONSISTENCY = "QUORUM"
```

should be 

``` python
CASSANDRA_CONSISTENCY = 4
```

found the solution here http://datastax.github.io/python-driver/api/cassandra.html#cassandra.ConsistencyLevel
